{{- if .Values.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "runmarket-loadtest.fullname" . }}-job
  labels:
    app.kubernetes.io/name: {{ include "runmarket-loadtest.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "runmarket-loadtest.name" . }}
    spec:
      containers:
      - name: k6
        image: "{{ .Values.k6.image.repository }}:{{ .Values.k6.image.tag }}"
        imagePullPolicy: {{ .Values.k6.image.pullPolicy }}
        command: ["k6", "run", "/scripts/pacer_load_test.js"]
        env:
        - name: API_BASE_URL
          value: {{ .Values.target.apiBaseUrl | quote }}
        - name: WS_BASE_URL
          value: {{ .Values.target.wsBaseUrl | quote }}
        - name: AUTH_BEARER_TOKEN
          value: {{ .Values.target.authToken | quote }}
        - name: K6_TARGET_VUS
          value: {{ .Values.loadProfile.targetVus | quote }}
        - name: K6_RAMP_UP
          value: {{ .Values.loadProfile.rampUpTime | quote }}
        - name: K6_HOLD_TIME
          value: {{ .Values.loadProfile.holdTime | quote }}
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: {{ .Release.Name }}-script
  backoffLimit: 0
{{- end -}}
