apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runmarket.fullname" . }}
  labels:
    {{- include "runmarket.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "runmarket.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "runmarket.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "runmarket.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ include "runmarket.postgresql.host" . | quote }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: {{ .Values.db.secretKeys.database }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: {{ .Values.db.secretKeys.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: {{ .Values.db.secretKeys.password }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.existingSecret }}
                  key: {{ .Values.app.secretKeys.jwtSecret }}
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.existingSecret }}
                  key: {{ .Values.app.secretKeys.mailPassword }}
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.existingSecret }}
                  key: {{ .Values.app.secretKeys.adminEmail }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.existingSecret }}
                  key: {{ .Values.app.secretKeys.adminPassword }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
