{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "runmarket-socket.fullname" . }}-redis
  labels:
    {{- include "runmarket-socket.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runmarket-socket.fullname" . }}-redis
  labels:
    {{- include "runmarket-socket.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "runmarket-socket.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "runmarket-socket.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "redis:{{ .Values.redis.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
            - --requirepass
            - $(REDIS_PASSWORD)
          ports:
            - name: redis
              containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: {{ .Values.db.secretKeys.redisPassword }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "runmarket-socket.fullname" . }}-redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "runmarket-socket.redis.host" . }}
  labels:
    {{- include "runmarket-socket.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "runmarket-socket.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
